# App: 'EITRI-SHOP-TEMPLATE-WAKE'
# DLK: 0647a5dd-5d7b-4ea1-888d-d86e05433f14
application-id: 0647a5dd-5d7b-4ea1-888d-d86e05433f14
bottom-tab-view-simulation:
    eitri-apps:
        - slug: 'home'
          title: 'Inicio'
          initialization-params:
              type: 'string'
              value: 'tabIndex=0'
        - slug: 'home'
          title: 'Categorias'
          initialization-params:
              type: 'string'
              value: 'tabIndex=1&route=Categories'
        - slug: 'cart'
          title: 'Carrinho'
          initialization-params:
              type: 'string'
              value: 'tabIndex=2'
        - slug: 'account'
          title: 'Perfil'
          initialization-params:
              type: 'string'
              value: 'tabIndex=3'
eitri-apps:
    - path: ./shopping-wake-template-shared
      workspace: shopping-wake-template-shared
      alias: shared
      focus: false
      shared: true
    - path: ./shopping-wake-template-home
      workspace: shopping-wake-template-home
      alias: home
      focus: true
      shared: false
    - path: ./shopping-wake-template-pdp
      workspace: shopping-wake-template-pdp
      alias: pdp
      focus: false
      shared: false
    - path: ./shopping-wake-template-cart
      workspace: shopping-wake-template-cart
      alias: cart
      focus: false
      shared: false
    - path: ./shopping-wake-template-checkout
      workspace: shopping-wake-template-checkout
      alias: checkout
      focus: false
      shared: false
    - path: ./shopping-wake-template-account
      workspace: shopping-wake-template-account
      alias: account
      focus: false
      shared: false
check-js: false
